# **Processamento de Linguagem Natural [2025-Q3]**
Prof. Alexandre Donizeti Alves

### **PROJETO PRÁTICO** [LangChain + Grandes Modelos de Linguagem]

O **PROJETO PRÁTICO** deve ser feito utilizando o **Google Colab** com uma conta sua vinculada ao Gmail. O link do seu notebook armazenado no Google Drive e o link de um repositório no GitHub devem ser enviados usando o seguinte formulário:

> https://forms.gle/D4gLqP1iGgyn2hbH8


**IMPORTANTE**: A submissão deve ser feita até o dia **07/12 (domingo)** APENAS POR UM INTEGRANTE DA EQUIPE, até às 23h59. Por favor, lembre-se de dar permissão de ACESSO IRRESTRITO para o professor da disciplina.

### **EQUIPE**

---

**POR FAVOR, PREENCHER OS INTEGRANDES DA SUA EQUIPE:**


**Integrante 01:**

`Gabriel Victor Lima Gonçalves RA: 11202230490`

**Integrante 02:**

`Por favor, informe o seu nome completo e RA:`

**Integrante 03:**

`Por favor, informe o seu nome completo e RA:`

### **GRANDE MODELO DE LINGUAGEM (*Large Language Model - LLM*)**

---

Cada equipe deve selecionar um Grande Modelo de Linguagem (*Large Language Model - LMM*).

Por favor, informe os dados do LLM selecionada:

>


**LLM**:

> chatgpt-5-nano OpenAI

**Link para a documentação oficial**:

> https://platform.openai.com/docs/api-reference/introduction

### **API (Opcional)**
---

Por favor, informe os dados da API selecionada:

**API**:

**Site oficial**:

**Link para a documentação oficial**:

### **DESCRIÇÃO**
---

Implementar um `notebook` no `Google Colab` que faça uso do framework **`LangChain`** (obrigatório) e de um **LLM** aplicando, no mínimo, DUAS técnicas de PLN. As técnicas podem ser aplicada em qualquer córpus obtido a partir de uma **API** ou a partir de uma página Web.

O **LLM** e a **API** selecionados devem ser informados na seguinte planilha:

> https://docs.google.com/spreadsheets/d/1iIUZcwnywO7RuF6VEJ8Rx9NDT1cwteyvsnkhYr0NWtU/edit?usp=sharing

>
As seguintes técnicas de PLN podem ser usadas:

*   Correção Gramatical
*   Classificação de Textos
*   Análise de Sentimentos
*   Detecção de Emoções
*   Extração de Palavras-chave
*   Tradução de Textos
*   Sumarização de Textos
*   Similaridade de Textos
*   Reconhecimento de Entidades Nomeadas
*   Sistemas de Perguntas e Respostas
>

**IMPORTANTE:** É obrigatório usar o e-mail da UFABC.

### **CRITÉRIOS DE AVALIAÇÃO**
---

Serão considerados como critérios de avaliação os seguintes pontos:

* Uso do framework **`LangChain`**.

* Escolha e uso de um **LLM**.

* Escolha e uso de uma **API** ou **Página Web**.

* Projeto disponível no Github.

* Apresentação (5 a 10 minutos).

* Criatividade no uso do framework **`LangChain`** em conjunto com o **LLM** e a **API**.

**IMPORTANTE**: todo o código do notebook deve ser executado. Código sem execução não será considerado.

### **IMPLEMENTAÇÃO**
---

# Final

In [10]:
# por favor, inserir o código a partir daqui...

# Estruturação

## Pipeline Recebendo os dados da API e tratando

## Pipeline Final Resumida

### Request da API filtrando areas tech

In [3]:
#Imports
import os
import re
import json
import requests
from pathlib import Path

In [4]:
import os
import json
import re
import requests


def pipeline_remotive_tech_jobs():
    """
    Pipeline completo:
    - Faz o request para a API da Remotive
    - Filtra SOMENTE vagas tech
    - Salva em ../data/raw/tech_jobs.json
    """

    # Categorias tech
    TECH_CATEGORIES = [
        "software-development",
        "ai-ml",
        "data",
        "devops",
        "qa"
    ]

    def slugify_category(text: str) -> str:
        return re.sub(r"\s+", "-", text.strip().lower())

    url = "https://remotive.com/api/remote-jobs"

    # ---- REQUEST ----
    try:
        response = requests.get(url, timeout=20)
        response.raise_for_status()
    except Exception as e:
        print(f"❌ Erro ao fazer request: {e}")
        return

    data = response.json()
    raw_jobs = data.get("jobs", [])

    # ---- FILTRAGEM ----
    tech_jobs = []
    for job in raw_jobs:
        category_raw = job.get("category", "")
        category_slug = slugify_category(category_raw)

        if category_slug in TECH_CATEGORIES:
            tech_jobs.append(job)

    # ---- SAVE JSON ----
    save_path = os.path.join("..", "data", "raw", "tech_jobs.json")
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(tech_jobs, f, ensure_ascii=False, indent=4)

    print(f"✔ Arquivo salvo em: {save_path}")
    print(f"✔ Salvo {len(tech_jobs)} tech jobs em tech_jobs.json")


#pipeline_remotive_tech_jobs()

### Recebe dados da API e faz tratamento inicial

In [5]:

# =========================================================
# 1. CLEAN HTML
# =========================================================
def clean_html(text: str) -> str:
    """Remove todas as tags HTML."""
    return re.sub(r"<[^>]+>", "", text or "")


# =========================================================
# 2. CLEAN JOB LIST (caso use o retorno da API diretamente)
# =========================================================
def clean_jobs(raw_json: dict) -> list:
    """
    Recebe o JSON da API e retorna uma nova lista de jobs com description limpa.
    """
    raw_jobs = raw_json["jobs"]
    cleaned = []

    for job in raw_jobs:
        new_job = job.copy()
        new_job["description"] = clean_html(job.get("description", ""))
        cleaned.append(new_job)

    return cleaned


# =========================================================
# 3. LOAD SUPPORT MAPS (tech + soft)
# =========================================================
def load_support_maps(support_dir: Path):
    with open(support_dir / "tech_stack.json", "r", encoding="utf-8") as f:
        tech_map = json.load(f)

    with open(support_dir / "soft_skills.json", "r", encoding="utf-8") as f:
        soft_map = json.load(f)

    # Normalize tudo para lowercase
    tech_map = {k.lower(): [v.lower() for v in values] for k, values in tech_map.items()}
    soft_map = {k.lower(): [v.lower() for v in values] for k, values in soft_map.items()}

    return tech_map, soft_map


# =========================================================
# 4. EXTRACT SKILL (macro + variações usadas)
#     → AGORA USANDO REGEX QUE GARANTE PALAVRA INTEIRA
#     → NÃO TEM MAIS FALSOS POSITIVOS (go, r, c...)
# =========================================================
def extract_skill_map(description: str, skill_map: dict):
    desc = description.lower()
    found = {}

    for macro, variations in skill_map.items():
        matches = []

        for var in variations:
            # Regex para casar palavra/frase inteira
            pattern = r"\b" + re.escape(var.lower()) + r"\b"

            if re.search(pattern, desc):
                matches.append(var)
                # Remove para evitar duplicações
                desc = re.sub(pattern, " ", desc)

        if matches:
            found[macro] = sorted(set(matches))  # organiza e remove duplicadas

    # Limpa excessos de espaços após substituições
    desc = re.sub(r"\s+", " ", desc).strip()

    return desc, found


# =========================================================
# 5. PROCESS A SINGLE JOB
# =========================================================
def process_job(job, tech_map, soft_map):
    desc = clean_html(job.get("description", "")).lower()

    # tech
    desc, tech_matches = extract_skill_map(desc, tech_map)

    # soft
    desc, soft_matches = extract_skill_map(desc, soft_map)

    job["description"] = desc
    job["tech_stacks_found"] = tech_matches
    job["soft_skills_found"] = soft_matches

    job.pop("tags", None)

    return job


# =========================================================
# 6. MAIN PIPELINE
# =========================================================
def pipeline(
    raw_path: Path = Path("../data/raw/tech_jobs.json"),
    processed_path: Path = Path("../data/processed/jobs_processed.json"),
    support_dir: Path = Path("../support")
):
    # Load tech+soft reference maps
    tech_map, soft_map = load_support_maps(support_dir)

    # Load raw jobs
    with open(raw_path, "r", encoding="utf-8") as f:
        raw_jobs = json.load(f)

    # Process everything
    processed = [process_job(job, tech_map, soft_map) for job in raw_jobs]

    # Ensure output directory exists
    processed_path.parent.mkdir(parents=True, exist_ok=True)

    # Save JSON
    with open(processed_path, "w", encoding="utf-8") as f:
        json.dump(processed, f, indent=4, ensure_ascii=False)

    print(f"✔ Arquivo salvo em: {processed_path}")


# =========================================================
# RUN DIRECTLY
# =========================================================

## pipeline trata dados diretamente do arquivo ../data/raw/tech_jobs.json bruto recebido após request da api e salva em ../data/processed/jobs_processed.json
#pipeline()

### Embedding Pipe

In [6]:
import pandas
from langchain_openai import OpenAIEmbeddings
from dotenv import load_dotenv

load_dotenv()  # procura automaticamente um .env ou .config no projeto
key = os.getenv("openai")
embeddings = OpenAIEmbeddings(
    model="text-embedding-3-large",
    api_key= key
    )

In [7]:
def generate_embeddings_df(
        
    path_json="../data/processed/jobs_processed.json",
    output_csv="../data/processed/jobs_with_embeddings.csv",
    model_name="text-embedding-3-large",
):
    
    """
    Carrega o JSON processado, trata colunas, gera embeddings e salva CSV final.
    Retorna o dataframe resultante.
    """

    # 1. Carregar dataframe
    df = pd.read_json(path_json)

    # 2. Colunas que precisam ser convertidas de str -> list
    cols_list = ["tech_stacks_found", "soft_skills_found"]

    for col in cols_list:
        df[col] = df[col].apply(
            lambda x: ast.literal_eval(x) if isinstance(x, str) else x
        )

    # 4. Gerar embeddings
    df["embedding"] = df["description"].apply(embeddings.embed_query)

    # 5. Salvar CSV final
    df.to_csv(output_csv, index=False)

    print(f"✅ CSV salvo em: {output_csv}")

    return df

### Nota currículo

In [8]:
curriculo = """GABRIEL VICTOR LIMA GONC¸ ALVES
+55 (11)94924-4811 ⋄ Santo Andr´e, SP
gabrielvgonc@gmail.com ⋄ www.linkedin.com/in/gabriel-victor-71187b223
OBJECTIVE
Seeking career growth opportunities in the field of software development.
EDUCATION
Bachelor of Computer Science, Universidade Federal do ABC Expected Graduation: 2026
SKILLS
Main Technical Skills Python, SQL, ETL, Java, Git
Soft Skills Communication, Adaptability, Analytical Thinking, Proactivity
Github Portfolio https://github.com/Netreck
Languages English, Portuguese
PROFESSIONAL EXPERIENCE
Intern – Bank of America Jun 2025 – Present
VP Global Technology – Tech Rotation Program
• Developed test automation and tools to support QA teams in payment systems.
• Contributed to internal automation and process optimization projects.
• Technologies: Java, Python, Git, SQL, Node.js, HTML, CSS, Octane, QTest, Matera.
Data Intern – Vivo (Telefˆonica Brasil) Jan 2025 – Jun 2025
VP Engineering & Customer Services
• Generated, monitored, and analyzed operational KPIs focused on efficiency and customer experience.
• Built Machine Learning solutions to modernize and improve operational results.
• Technologies: Python, SQL, TensorFlow, Power BI, Excel.
EXTRACURRICULAR ACTIVITIES
Member – Green Team Hacker Club Jan 2024 – Jan 2025
Project Manager – Data Projects, Green Team Hacker Club Jan 2025 – Present
Federal University of ABC (UFABC) Santo Andr´e, SP
• Official student-led organization linked to UFABC.
• Participated in classes and projects related to Data Science.
• Defined and managed technology stack for projects, considering scalability, performance, and integration.
• Managed team activities including task delegation, progress tracking, and technical support.
• Worked with ETL, process automation (pipelines), SQL, PostgreSQL, Data Visualization (Seaborn,
Matplotlib), Data Modeling, Machine Learning models (Scikit-learn, TensorFlow), model deployment
via APIs, MLflow, and LLMs.
"""

In [9]:
def run_matching_pipeline(curriculo_str):

    # ================================================
    # IMPORTS
    # ================================================
    import json, re, ast, os
    import pandas as pd
    import numpy as np
    from pathlib import Path
    from dotenv import load_dotenv
    from sklearn.metrics.pairwise import cosine_similarity
    from langchain_openai import OpenAIEmbeddings


    # ================================================
    # SUPPORT MAPS
    # ================================================
    def load_support_maps(support_dir: Path):
        with open(support_dir / "tech_stack.json", "r", encoding="utf-8") as f:
            tech_map = json.load(f)

        with open(support_dir / "soft_skills.json", "r", encoding="utf-8") as f:
            soft_map = json.load(f)

        tech_map = {k.lower(): [v.lower() for v in values] for k, values in tech_map.items()}
        soft_map = {k.lower(): [v.lower() for v in values] for k, values in soft_map.items()}

        return tech_map, soft_map


    # ================================================
    # EXTRACT SKILL
    # ================================================
    def extract_skill_map(description: str, skill_map: dict):
        desc = description.lower()
        found = {}

        for macro, variations in skill_map.items():
            matches = []
            for var in variations:
                if var in desc:
                    matches.append(var)
                    desc = desc.replace(var, "")

            if matches:
                found[macro] = matches

        desc = re.sub(r"\s+", " ", desc).strip()
        return desc, found


    # ================================================
    # PROCESS CURRICULO
    # ================================================
    def process_curriculo(curriculo: str, support_dir: Path = Path("../support")):

        load_dotenv()
        api_key = os.getenv("openai")
        if not api_key:
            raise ValueError("❌ OPENAI_API_KEY não encontrada no .env")

        tech_map, soft_map = load_support_maps(support_dir)

        clean_curriculo = re.sub(r"\s+", " ", curriculo).strip()

        desc_after_tech, tech_found = extract_skill_map(clean_curriculo, tech_map)
        desc_after_soft, soft_found = extract_skill_map(desc_after_tech, soft_map)

        embeddings = OpenAIEmbeddings(
            model="text-embedding-3-large",
            api_key=api_key
        )

        embedding_vector = embeddings.embed_query(clean_curriculo)

        return {
            "curriculo_raw": curriculo,
            "curriculo_clean": clean_curriculo,
            "embedding": embedding_vector,
            "tech_stacks_found": tech_found,
            "soft_skills_found": soft_found
        }


    # ================================================
    # FINAL SCORE
    # ================================================
    def compute_final_score(similarity_raw, sim_min, sim_max,
                            job_techs, job_soft,
                            curr_techs, curr_soft):

        similarity_norm = (similarity_raw - sim_min) / (sim_max - sim_min + 1e-9)
        similarity_norm = max(0, min(1, similarity_norm))

        # Tech score
        total_tech = len(job_techs)
        tech_val = (
            sum(1 for macro in job_techs if macro in curr_techs) / total_tech
            if total_tech > 0 else 1
        )

        # Soft score
        total_soft = len(job_soft)
        soft_val = (
            sum(1 for macro in job_soft if macro in curr_soft) / total_soft
            if total_soft > 0 else 1
        )

        final = (
            0.8 * similarity_norm +
            0.1 * tech_val +
            0.1 * soft_val
        ) * 100

        return round(final, 2)


    # ================================================
    # PRINT BONITO
    # ================================================
    def print_job_match(row, index):
        print("======================================================================")
        print(f"📌 Job #{index}")
        print(f"🏷️  Title: {row['title']}")
        print(f"🏢 Company: {row['company_name']}")
        print(f"🔧 Tech Stacks Found: {row['tech_stacks_found']}")
        print(f"📊 Similarity: {round(row['embedding_similarity'], 4)}")
        print(f"🔥 Compatibility Score: {row['compatibility_score']}")
        print("----------------------------------------------------------------------")
        print("📝 Description:")
        desc = row['description']
        if len(desc) > 500:
            desc = desc[:500] + "..."
        print(desc)
        print("======================================================================\n\n")


    # ================================================
    # EXECUÇÃO FINAL
    # ================================================

    # 1. Processa currículo
    resultado = process_curriculo(curriculo_str)

    # 2. Carrega CSV
    df = pd.read_csv("../data/processed/jobs_with_embeddings.csv")

    # 3. Converte strings → dict/list
    cols_to_fix = ["tech_stacks_found", "soft_skills_found", "embedding"]
    for col in cols_to_fix:
        df[col] = df[col].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

    # 4. Similaridade
    curr_emb = np.array(resultado["embedding"]).reshape(1, -1)

    df["embedding_similarity"] = df["embedding"].apply(
        lambda v: float(
            cosine_similarity(curr_emb, np.array(v).reshape(1, -1))[0][0]
        )
    )

    # 5. Score final
    sim_min = df["embedding_similarity"].min()
    sim_max = df["embedding_similarity"].max()

    df["compatibility_score"] = df.apply(lambda row:
        compute_final_score(
            similarity_raw=row["embedding_similarity"],
            sim_min=sim_min,
            sim_max=sim_max,
            job_techs=row["tech_stacks_found"],
            job_soft=row["soft_skills_found"],
            curr_techs=resultado["tech_stacks_found"],
            curr_soft=resultado["soft_skills_found"]
        ),
        axis=1
    )

    # 6. Ordena
    df_sorted = df.sort_values(by="compatibility_score", ascending=False)

    # 7. Print bonito (Top 10)
    for i, row in df_sorted.head(100).iterrows():
        print_job_match(row, i)

In [10]:
import json
import re
from pathlib import Path


# =========================================================
# 1. LOAD SUPPORT MAPS (tech + soft)
# =========================================================
def load_support_maps(support_dir: Path):
    with open(support_dir / "tech_stack.json", "r", encoding="utf-8") as f:
        tech_map = json.load(f)

    with open(support_dir / "soft_skills.json", "r", encoding="utf-8") as f:
        soft_map = json.load(f)

    tech_map = {k.lower(): [v.lower() for v in values] for k, values in tech_map.items()}
    soft_map = {k.lower(): [v.lower() for v in values] for k, values in soft_map.items()}

    return tech_map, soft_map


# =========================================================
# 2. **EXTRACT SKILL CORRIGIDO** (match por palavra inteira)
# =========================================================
def extract_skill_map(description: str, skill_map: dict):
    desc = description.lower()
    found = {}

    for macro, variations in skill_map.items():
        matches = []

        for var in variations:
            # Regex para casar palavra inteira — evita falsos positivos
            pattern = r"\b" + re.escape(var.lower()) + r"\b"

            if re.search(pattern, desc):
                matches.append(var)
                # Remove a ocorrência encontrada para evitar duplicação
                desc = re.sub(pattern, " ", desc)

        if matches:
            found[macro] = sorted(set(matches))

    desc = re.sub(r"\s+", " ", desc).strip()
    return desc, found


# =========================================================
# 3. PIPELINE DO CURRÍCULO (SEM EMBEDDING)
# =========================================================
def process_curriculo(
    curriculo: str,
    support_dir: Path = Path("../support")
):
    tech_map, soft_map = load_support_maps(support_dir)

    clean_curriculo = re.sub(r"\s+", " ", curriculo).strip()

    # Extrai tech
    desc_after_tech, tech_found = extract_skill_map(clean_curriculo, tech_map)
    # Extrai soft
    desc_after_soft, soft_found = extract_skill_map(desc_after_tech, soft_map)

    # Mesma estrutura de uma vaga
    return {
        "description": clean_curriculo,
        "tech_stacks_found": tech_found,
        "soft_skills_found": soft_found
    }


# =========================================================
# 4. PRINT BONITO — MESMO FORMATO DAS VAGAS
# =========================================================
def print_curriculo_formatado(resultado):
    print("======================================================================")
    print("📌 CURRÍCULO PROCESSADO")
    print("🔧 Tech Stacks Found:", resultado["tech_stacks_found"])
    print("🧩 Soft Skills Found:", resultado["soft_skills_found"])
    print("----------------------------------------------------------------------")
    print("📝 Description:")

    desc = resultado["description"]
    if len(desc) > 700:
        desc = desc[:700] + "..."

    print(desc)
    print("======================================================================\n")


# =========================================================
# 5. FUNÇÃO FINAL
# =========================================================
def run_curriculo_preview(curriculo_str):
    resultado = process_curriculo(curriculo_str)
    print_curriculo_formatado(resultado)
    return resultado

In [11]:
run_curriculo_preview(curriculo)

======================================================================
📌 CURRÍCULO PROCESSADO
🔧 Tech Stacks Found: {'languages': ['java', 'python'], 'backend_frameworks': ['node'], 'databases_sql': ['postgresql'], 'ml_ai': ['scikit-learn', 'tensorflow'], 'bi_analytics': ['power bi'], 'others_general': ['automation', 'computer science', 'css', 'data science', 'data visualization', 'etl', 'excel', 'git', 'github', 'html', 'sql', 'technical support']}
🧩 Soft Skills Found: {'communication': ['communication'], 'leadership': ['delegation'], 'problem_solving': ['analytical thinking'], 'adaptability': ['adaptability'], 'time_management': ['organization'], 'work_style': ['proactivity'], 'others_general': ['soft skills']}
----------------------------------------------------------------------
📝 Description:
GABRIEL VICTOR LIMA GONC¸ ALVES +55 (11)94924-4811 ⋄ Santo Andr´e, SP gabrielvgonc@gmail.com ⋄ www.linkedin.com/in/gabriel-victor-71187b223 OBJECTIVE Seeking career growth opportunities in the field of software development. EDUCATION Bachelor of Computer Science, Universidade Federal do ABC Expected Graduation: 2026 SKILLS Main Technical Skills Python, SQL, ETL, Java, Git Soft Skills Communication, Adaptability, Analytical Thinking, Proactivity Github Portfolio https://github.com/Netreck Languages English, Portuguese PROFESSIONAL EXPERIENCE Intern – Bank of America Jun 2025 – Present VP Global Technology – Tech Rotation Program • Developed test automation and tools to support QA teams in pay...
======================================================================

{'description': 'GABRIEL VICTOR LIMA GONC¸ ALVES +55 (11)94924-4811 ⋄ Santo Andr´e, SP gabrielvgonc@gmail.com ⋄ www.linkedin.com/in/gabriel-victor-71187b223 OBJECTIVE Seeking career growth opportunities in the field of software development. EDUCATION Bachelor of Computer Science, Universidade Federal do ABC Expected Graduation: 2026 SKILLS Main Technical Skills Python, SQL, ETL, Java, Git Soft Skills Communication, Adaptability, Analytical Thinking, Proactivity Github Portfolio https://github.com/Netreck Languages English, Portuguese PROFESSIONAL EXPERIENCE Intern – Bank of America Jun 2025 – Present VP Global Technology – Tech Rotation Program • Developed test automation and tools to support QA teams in payment systems. • Contributed to internal automation and process optimization projects. • Technologies: Java, Python, Git, SQL, Node.js, HTML, CSS, Octane, QTest, Matera. Data Intern – Vivo (Telefˆonica Brasil) Jan 2025 – Jun 2025 VP Engineering & Customer Services • Generated, monitored, and analyzed operational KPIs focused on efficiency and customer experience. • Built Machine Learning solutions to modernize and improve operational results. • Technologies: Python, SQL, TensorFlow, Power BI, Excel. EXTRACURRICULAR ACTIVITIES Member – Green Team Hacker Club Jan 2024 – Jan 2025 Project Manager – Data Projects, Green Team Hacker Club Jan 2025 – Present Federal University of ABC (UFABC) Santo Andr´e, SP • Official student-led organization linked to UFABC. • Participated in classes and projects related to Data Science. • Defined and managed technology stack for projects, considering scalability, performance, and integration. • Managed team activities including task delegation, progress tracking, and technical support. • Worked with ETL, process automation (pipelines), SQL, PostgreSQL, Data Visualization (Seaborn, Matplotlib), Data Modeling, Machine Learning models (Scikit-learn, TensorFlow), model deployment via APIs, MLflow, and LLMs.',
 'tech_stacks_found': {'languages': ['java', 'python'],
  'backend_frameworks': ['node'],
  'databases_sql': ['postgresql'],
  'ml_ai': ['scikit-learn', 'tensorflow'],
  'bi_analytics': ['power bi'],
  'others_general': ['automation',
   'computer science',
   'css',
   'data science',
   'data visualization',
   'etl',
   'excel',
   'git',
   'github',
   'html',
   'sql',
   'technical support']},
 'soft_skills_found': {'communication': ['communication'],
  'leadership': ['delegation'],
  'problem_solving': ['analytical thinking'],
  'adaptability': ['adaptability'],
  'time_management': ['organization'],
  'work_style': ['proactivity'],
  'others_general': ['soft skills']}}

In [15]:
#resultado = process_curriculo(curriculo)
run_matching_pipeline(curriculo)

======================================================================
📌 Job #103
🏷️  Title: Software Developer - Intern
🏢 Company: SYSTEM AUTOMATION CORPORATION
🔧 Tech Stacks Found: {'languages': ['java', 'javascript'], 'others_general': ['automation', 'cloud', 'computer science', 'documentation', 'product development', 'saas', 'solid', 'sql', 'testing']}
📊 Similarity: 0.4037
🔥 Compatibility Score: 88.62
----------------------------------------------------------------------
📝 Description:
apply job type internship description internship summer period -early december through mid january 2026about the company system (sa) is a software vendor focused on providing systems that support government regulatory management operations.founded in the district of columbia in 1968 and originally contracted to develop and support the us army recruiting system (contract held for 42 years), sa has since become an industry leader in designing, developing, implementing, and maintaining comprehensiv...
======================================================================


======================================================================
📌 Job #135
🏷️  Title: Python Developer
🏢 Company: Hotelogix India Private Limited
🔧 Tech Stacks Found: {'languages': ['javascript', 'python'], 'backend_frameworks': ['django', 'flask'], 'others_general': ['api', 'cloud', 'computer science', 'debugging', 'git', 'responsive', 'security', 'testing']}
📊 Similarity: 0.3941
🔥 Compatibility Score: 85.52
----------------------------------------------------------------------
📝 Description:
we are currently hiring a developer to join our engineering team to developdynamic software applications.experience - 3-5yearsmain responsibilities of a developer writing effective and scalable codes designing and implementing robust applications applications to ensure low-latency and high-availability integrating user-facing elements with server-side logic implementing and data protection accommodating various data storage solutions develop complete secured application and back-end modul...
======================================================================


======================================================================
📌 Job #44
🏷️  Title: Full Stack Developer
🏢 Company: Redbee
🔧 Tech Stacks Found: {'languages': ['c', 'java'], 'frontend_frameworks': ['angular', 'react'], 'backend_frameworks': ['spring'], 'others_general': ['backend', 'cloud', 'frontend', 'git', 'rest', 'testing']}
📊 Similarity: 0.388
🔥 Compatibility Score: 83.57
----------------------------------------------------------------------
📝 Description:
buscamos profesionales con curiosidad y pasión, jugadores de equipo, que quieran crecer, innovar y aprender de las últimas tecnologías. hacemos diferente y estamos en movimiento!tenemos una cultura a. .t.i.va y nuestro propósito es ayudarte a elegir el mejor camino para que la rompas.¿qué vas a hacer?desarrollar y evolucionar funcionalidades del canal online en un entorno de modernización tecnológica.trabajar sobre una arquitectura híbrida con , y servicios , colaborando con equipos multidiscipl...
======================================================================


======================================================================
📌 Job #87
🏷️  Title: Systems Analyst
🏢 Company: Dev.Pro
🔧 Tech Stacks Found: {'cloud': ['aws', 'azure'], 'devops': ['docker', 'k8s'], 'databases_nosql': ['mongodb'], 'infra': ['apache', 'linux', 'nginx'], 'monitoring': ['datadog', 'grafana', 'prometheus'], 'productivity': ['jira'], 'others_general': ['cloud', 'documentation', 'fintech', 'hardware', 'infrastructure', 'insurance', 'it support', 'retail', 'technical support', 'troubleshooting']}
📊 Similarity: 0.4392
🔥 Compatibility Score: 81.43
----------------------------------------------------------------------
📝 Description:
🟢 are you in brazil, argentina or colombia? join us as we actively recruit in these locations, offering a comfortable remote environment. submit your cv in english, and we'll get back to you!we invite a responsible and eager-to-learn network operations center engineer to join our 24/7 support team, helping ensure the stability and performance of client applications and . our client provides retailers with a centralized, flexible, and secure payment platform that enables customers to shop anytime...
======================================================================


======================================================================
📌 Job #75
🏷️  Title: Front-End Engineer
🏢 Company: Trustly
🔧 Tech Stacks Found: {'languages': ['java', 'javascript'], 'frontend_frameworks': ['react'], 'backend_frameworks': ['node'], 'mobile': ['android'], 'others_general': ['backend', 'css', 'documentation', 'es6', 'html', 'ios', 'software systems']}
📊 Similarity: 0.417
🔥 Compatibility Score: 80.86
----------------------------------------------------------------------
📝 Description:
about the team: the developer experience team is responsible for the publicly available developer , sdks &amp; libraries, apis, and other developer tools and processes. our focus is to offer the best experience for developers and make trustly the payment option developers prefer and recommend.what you'll do:create and maintain features in web including integration scripts applications and be able to develop unit tests for the same features.responsible for investigating problems in applications i...
======================================================================


======================================================================
📌 Job #88
🏷️  Title: Python Engineer
🏢 Company: TechBiz Global GmbH
🔧 Tech Stacks Found: {'languages': ['bash', 'python'], 'backend_frameworks': ['django'], 'cloud': ['aws'], 'devops': ['docker', 'kubernetes', 'terraform'], 'databases_sql': ['mysql', 'postgresql'], 'monitoring': ['grafana'], 'productivity': ['confluence', 'jira'], 'others_general': ['agile', 'cloud', 'fintech', 'scripting', 'scrum', 'solid', 'sql']}
📊 Similarity: 0.4248
🔥 Compatibility Score: 79.13
----------------------------------------------------------------------
📝 Description:
at techbiz global, we are providing recruitment service to our top clients from our portfolio. we are currently seeking a engineer to join one of our clients' teams. if you're looking for an exciting opportunity to grow in a innovative environment, this could be the perfect fit for you.what you will do:develop and maintain applications.deliver and maintainable software.translate business requirements into technical solutions.implement, review, support and debug required scopewrite tech specs and...
======================================================================


======================================================================
📌 Job #159
🏷️  Title: Senior Quality Assurance Automation Engineer
🏢 Company: AlphaSights
🔧 Tech Stacks Found: {'languages': ['java', 'javascript', 'python', 'typescript'], 'devops': ['kubernetes'], 'testing': ['cypress', 'playwright'], 'others_general': ['automation', 'backend', 'cloud', 'distributed systems', 'frontend', 'infrastructure', 'manual testing', 'mentoring', 'nosql', 'product management', 'security', 'sql', 'testing']}
📊 Similarity: 0.4155
🔥 Compatibility Score: 79.06
----------------------------------------------------------------------
📝 Description:
the role: alphasights is seeking a highly experienced, self-driven senior qa engineer to join our software engineering team. we are a digital business in which continuous uptime, product quality, and user experience are critical to success. the role of the qa engineer therefore represents a visible and valued opportunity to have an immediate impact. working alongside software engineering and , you will lead the design and implementation of automated solutions that scale across our platform, ensu...
======================================================================


======================================================================
📌 Job #238
🏷️  Title: Senior Java Developer
🏢 Company: Penguin Formula
🔧 Tech Stacks Found: {'languages': ['go', 'java', 'python'], 'frontend_frameworks': ['angular'], 'backend_frameworks': ['spring'], 'cloud': ['aws'], 'devops': ['docker', 'kubernetes'], 'databases_sql': ['mysql', 'postgresql'], 'big_data': ['kafka'], 'messaging': ['rabbitmq'], 'others_general': ['api', 'automation', 'backend', 'cloud', 'debugging', 'distributed systems', 'frontend', 'infrastructure', 'nosql', 'rest', 'security', 'solid', 'sql']}
📊 Similarity: 0.4158
🔥 Compatibility Score: 76.95
----------------------------------------------------------------------
📝 Description:
company descriptionwecookit is an international software house that delivers software development to its corporate customers by providing highly skilled, communicative it professionals to build their customized products through outsourcing, nearshoring and turn-key projects’ solutions.how do we differentiate ourselves? by investing in the professional growth and personal care of our software developers. we provide them with a premium service so that they can do the same for our customers.our tal...
======================================================================


======================================================================
📌 Job #217
🏷️  Title: Senior Platform Engineer
🏢 Company: Feedzai
🔧 Tech Stacks Found: {'languages': ['go', 'python'], 'cloud': ['aws', 'gcp'], 'devops': ['docker', 'kubernetes', 'terraform'], 'cicd': ['jenkins'], 'monitoring': ['grafana', 'prometheus'], 'others_general': ['automation', 'cloud', 'computer science', 'data science', 'distributed systems', 'diversity', 'gitlab', 'infrastructure', 'nosql', 'product development', 'product management', 'risk management', 'security']}
📊 Similarity: 0.4175
🔥 Compatibility Score: 76.36
----------------------------------------------------------------------
📝 Description:
feedzai is the world’s first riskops platform for financial , and the market leader in safeguarding global commerce with today’s most advanced -based platform, powered by machine learning and artificial intelligence. feedzai is securing the transition to a cashless world while enabling digital trust in every transaction and payment type. the world’s largest banks, processors, and retailers trust feedzai to protect trillions of dollars and manage risk while improving the customer experience for e...
======================================================================


======================================================================
📌 Job #160
🏷️  Title: Backend Developer Support
🏢 Company: Rocket Code (AL-I Digital Solutions S.A. de C.V.)
🔧 Tech Stacks Found: {'languages': ['bash', 'python'], 'backend_frameworks': ['node'], 'cloud': ['aws', 'gcp'], 'databases_sql': ['mysql', 'postgresql'], 'databases_nosql': ['mongodb'], 'others_general': ['automation', 'backend', 'cloud', 'debugging', 'fintech', 'git', 'postman', 'scripting', 'solid', 'technical support']}
📊 Similarity: 0.4082
🔥 Compatibility Score: 75.05
----------------------------------------------------------------------
📝 Description:
join the ai revolution with rocket code!at rocket code, we're not just developers — we're dreamers, doers, and disruptors. as a rapidly growing company renowned for building and optimizing technological platforms, we are at the forefront of making ai work for you, turning market buzz into groundbreaking realities. our disruptive, ai-first approach drives us to seek new ways of working, prioritizing operational efficiency and transforming the software development industry. we need passionate indi...
======================================================================


======================================================================
📌 Job #284
🏷️  Title: Data Scientist
🏢 Company: CloudWalk
🔧 Tech Stacks Found: {'languages': ['python'], 'cloud': ['google cloud'], 'ml_ai': ['pytorch', 'tensorflow'], 'others_general': ['cloud', 'data science', 'data visualization', 'distributed systems', 'fintech', 'research', 'risk management', 'solid', 'sql']}
📊 Similarity: 0.4065
🔥 Compatibility Score: 74.52
----------------------------------------------------------------------
📝 Description:
about cloudwalk:we are not just another unicorn. we are a pack of dreamers, makers, and tech enthusiasts building the future of payments. with millions of happy customers and a hunger for , we're now expanding our neural network - literally and metaphorically.about the team:the risk team is responsible for building the defense layer that keeps cloudwalk, its merchants, and users safe. we keep our ecosystem healthy by tracking down malicious activity and maintaining regulatory compliance while pr...
======================================================================


======================================================================
📌 Job #265
🏷️  Title: Senior Fullstack Developer
🏢 Company: Redbee
🔧 Tech Stacks Found: {'languages': ['c'], 'frontend_frameworks': ['react'], 'others_general': ['graphql', 'rest']}
📊 Similarity: 0.3596
🔥 Compatibility Score: 74.49
----------------------------------------------------------------------
📝 Description:
buscamos profesionales con curiosidad y pasión, jugadores de equipo, que quieran crecer, innovar y aprender de las últimas tecnologías. hacemos diferente y estamos en movimiento!tenemos una cultura a. .t.i.va y nuestro propósito es ayudarte a elegir el mejor camino para que la rompas.¿qué hacemos como senior developer en redbee?desarrollar nuevas funcionalidades en aplicaciones utilizando nest.js y , bff, arquitecturas orientadas a microservicios. escribir código bien estructurado asegurando man...
======================================================================


======================================================================
📌 Job #153
🏷️  Title: Senior Backend Software Engineer
🏢 Company: Squad
🔧 Tech Stacks Found: {'languages': ['python'], 'cloud': ['aws'], 'others_general': ['cloud', 'healthcare', 'infrastructure', 'mental health', 'product development', 'saas', 'security', 'startup', 'system architecture']}
📊 Similarity: 0.3973
🔥 Compatibility Score: 74.33
----------------------------------------------------------------------
📝 Description:
about our clientour client is a privately held, early-stage company pioneering the use of artificial intelligence to transform paradigms and develop a new category of psychological fitness. the is focused on creating a world where individuals and communities are empowered to proactively identify and address psychological challenges and concerns.this company is backed by a leading enterprise known for conceiving, building, and supporting ventures that invent breakthrough technologies across , agr...
======================================================================


======================================================================
📌 Job #253
🏷️  Title: Senior Data Engineer
🏢 Company: ID5
🔧 Tech Stacks Found: {'languages': ['java', 'kotlin', 'python'], 'frontend_frameworks': ['vue'], 'backend_frameworks': ['spring'], 'cloud': ['aws', 'azure', 'gcp'], 'devops': ['kubernetes'], 'databases_sql': ['postgres', 'snowflake'], 'databases_nosql': ['cassandra'], 'big_data': ['airflow', 'databricks', 'flink', 'kafka', 'spark', 'trino'], 'bi_analytics': ['superset'], 'infra': ['apache'], 'monitoring': ['grafana'], 'others_general': ['advertising', 'analytics', 'api', 'backend', 'cloud', 'computer science', 'data engineering', 'diversity', 'infrastructure', 'nosql', 'solid', 'sql']}
📊 Similarity: 0.4105
🔥 Compatibility Score: 74.14
----------------------------------------------------------------------
📝 Description:
id5 enables addressable and measurable to support the growth of the digital economy and provide free and safe access to content and services. technical changes, signal loss, and increasingly more stringent data protection regulations require new, advanced technologies that enable audience addressability while respecting people’s privacy preferences. id5 has risen to this challenge and developed solutions that support publishers’ and marketers’ need for better addressability. its laser focus on i...
======================================================================


======================================================================
📌 Job #280
🏷️  Title: AI Engineer
🏢 Company: Addepto
🔧 Tech Stacks Found: {'languages': ['python', 'typescript'], 'frontend_frameworks': ['react'], 'backend_frameworks': ['fastapi', 'node'], 'cloud': ['aws', 'azure', 'gcp'], 'devops': ['docker'], 'big_data': ['databricks'], 'others_general': ['backend', 'big data', 'cloud', 'data engineering', 'data science', 'documentation', 'frontend', 'git', 'infrastructure', 'nosql', 'onboarding', 'solid', 'sql']}
📊 Similarity: 0.3924
🔥 Compatibility Score: 74.04
----------------------------------------------------------------------
📝 Description:
addepto is a leading ai consulting and company that builds scalable, roi-focused ai solutions for some of the world's largest enterprises and pioneering startups, including rolls royce, continental, porsche, abb, and wgu. with our exclusive focus on artificial intelligence and , we help organizations unlock the full potential of their data through systems designed for measurable business impact and long-term growth.beyond client projects, we have developed our own product offerings born from rea...
======================================================================


======================================================================
📌 Job #227
🏷️  Title: Software Engineer Intern
🏢 Company: Branch International
🔧 Tech Stacks Found: {'languages': ['java', 'kotlin', 'python', 'ruby'], 'mobile': ['android'], 'others_general': ['backend', 'computer science', 'distributed systems', 'fintech', 'open source', 'solid']}
📊 Similarity: 0.3997
🔥 Compatibility Score: 74.02
----------------------------------------------------------------------
📝 Description:
branch overviewbranch is a leading ai-based lending with 50m+ downloads across india and africa. we use alternative data to reach millions of people that are largely excluded from the financial sector.headquartered in silicon valley with operations in india, nigeria and kenya, branch is a for-profit, socially conscious company built for scale and impact. our mission-driven team—founded and led by the former ceo of kiva.org—now spans 400+ employees globally. we’re backed by investors such as andr...
======================================================================


======================================================================
📌 Job #172
🏷️  Title: RPA Developer
🏢 Company: Realtime Analytics By Procalidad
🔧 Tech Stacks Found: {'languages': ['python'], 'cloud': ['aws', 'azure', 'google cloud'], 'others_general': ['automation', 'git', 'nlp', 'rest', 'scripting', 'sql']}
📊 Similarity: 0.3668
🔥 Compatibility Score: 73.46
----------------------------------------------------------------------
📝 Description:
rpa developer with ai/mlwe are looking for a motivated and goal-oriented rpa developer with artificial intelligence and machine learning to join our team. the rpa developer creates and maintains robotic process (rpa) solutions integrated with artificial intelligence and machine learning capabilities. designs intelligent bots that can learn, adapt, and make data-driven decisionskey responsibilities:✅ develop rpa bots using uipath, anywhere, or blue prism ✅ integrate ml models to improve automated...
======================================================================


======================================================================
📌 Job #222
🏷️  Title: Senior Angular Developer
🏢 Company: INNOCV Solutions S.L.U.
🔧 Tech Stacks Found: {'languages': ['javascript', 'typescript'], 'frontend_frameworks': ['angular'], 'others_general': ['agile', 'diversity', 'insurance', 'solid', 'testing', 'web applications']}

In [14]:
#resultado = process_curriculo(curriculo)
run_matching_pipeline(curriculo)

======================================================================
📌 Job #103
🏷️  Title: Software Developer - Intern
🏢 Company: SYSTEM AUTOMATION CORPORATION
🔧 Tech Stacks Found: {'languages': ['java', 'javascript'], 'others_general': ['automation', 'cloud', 'computer science', 'documentation', 'product development', 'saas', 'solid', 'sql', 'testing']}
📊 Similarity: 0.4036
🔥 Compatibility Score: 88.82
----------------------------------------------------------------------
📝 Description:
apply job type internship description internship summer period -early december through mid january 2026about the company system (sa) is a software vendor focused on providing systems that support government regulatory management operations.founded in the district of columbia in 1968 and originally contracted to develop and support the us army recruiting system (contract held for 42 years), sa has since become an industry leader in designing, developing, implementing, and maintaining comprehensiv...
======================================================================


======================================================================
📌 Job #135
🏷️  Title: Python Developer
🏢 Company: Hotelogix India Private Limited
🔧 Tech Stacks Found: {'languages': ['javascript', 'python'], 'backend_frameworks': ['django', 'flask'], 'others_general': ['api', 'cloud', 'computer science', 'debugging', 'git', 'responsive', 'security', 'testing']}
📊 Similarity: 0.3938
🔥 Compatibility Score: 85.67
----------------------------------------------------------------------
📝 Description:
we are currently hiring a developer to join our engineering team to developdynamic software applications.experience - 3-5yearsmain responsibilities of a developer writing effective and scalable codes designing and implementing robust applications applications to ensure low-latency and high-availability integrating user-facing elements with server-side logic implementing and data protection accommodating various data storage solutions develop complete secured application and back-end modul...
======================================================================


======================================================================
📌 Job #44
🏷️  Title: Full Stack Developer
🏢 Company: Redbee
🔧 Tech Stacks Found: {'languages': ['c', 'java'], 'frontend_frameworks': ['angular', 'react'], 'backend_frameworks': ['spring'], 'others_general': ['backend', 'cloud', 'frontend', 'git', 'rest', 'testing']}
📊 Similarity: 0.3878
🔥 Compatibility Score: 83.74
----------------------------------------------------------------------
📝 Description:
buscamos profesionales con curiosidad y pasión, jugadores de equipo, que quieran crecer, innovar y aprender de las últimas tecnologías. hacemos diferente y estamos en movimiento!tenemos una cultura a. .t.i.va y nuestro propósito es ayudarte a elegir el mejor camino para que la rompas.¿qué vas a hacer?desarrollar y evolucionar funcionalidades del canal online en un entorno de modernización tecnológica.trabajar sobre una arquitectura híbrida con , y servicios , colaborando con equipos multidiscipl...
======================================================================


======================================================================
📌 Job #87
🏷️  Title: Systems Analyst
🏢 Company: Dev.Pro
🔧 Tech Stacks Found: {'cloud': ['aws', 'azure'], 'devops': ['docker', 'k8s'], 'databases_nosql': ['mongodb'], 'infra': ['apache', 'linux', 'nginx'], 'monitoring': ['datadog', 'grafana', 'prometheus'], 'productivity': ['jira'], 'others_general': ['cloud', 'documentation', 'fintech', 'hardware', 'infrastructure', 'insurance', 'it support', 'retail', 'technical support', 'troubleshooting']}
📊 Similarity: 0.4385
🔥 Compatibility Score: 81.43
----------------------------------------------------------------------
📝 Description:
🟢 are you in brazil, argentina or colombia? join us as we actively recruit in these locations, offering a comfortable remote environment. submit your cv in english, and we'll get back to you!we invite a responsible and eager-to-learn network operations center engineer to join our 24/7 support team, helping ensure the stability and performance of client applications and . our client provides retailers with a centralized, flexible, and secure payment platform that enables customers to shop anytime...
======================================================================


======================================================================
📌 Job #75
🏷️  Title: Front-End Engineer
🏢 Company: Trustly
🔧 Tech Stacks Found: {'languages': ['java', 'javascript'], 'frontend_frameworks': ['react'], 'backend_frameworks': ['node'], 'mobile': ['android'], 'others_general': ['backend', 'css', 'documentation', 'es6', 'html', 'ios', 'software systems']}
📊 Similarity: 0.4169
🔥 Compatibility Score: 81.07
----------------------------------------------------------------------
📝 Description:
about the team: the developer experience team is responsible for the publicly available developer , sdks &amp; libraries, apis, and other developer tools and processes. our focus is to offer the best experience for developers and make trustly the payment option developers prefer and recommend.what you'll do:create and maintain features in web including integration scripts applications and be able to develop unit tests for the same features.responsible for investigating problems in applications i...
======================================================================


======================================================================
📌 Job #88
🏷️  Title: Python Engineer
🏢 Company: TechBiz Global GmbH
🔧 Tech Stacks Found: {'languages': ['bash', 'python'], 'backend_frameworks': ['django'], 'cloud': ['aws'], 'devops': ['docker', 'kubernetes', 'terraform'], 'databases_sql': ['mysql', 'postgresql'], 'monitoring': ['grafana'], 'productivity': ['confluence', 'jira'], 'others_general': ['agile', 'cloud', 'fintech', 'scripting', 'scrum', 'solid', 'sql']}
📊 Similarity: 0.4247
🔥 Compatibility Score: 79.34
----------------------------------------------------------------------
📝 Description:
at techbiz global, we are providing recruitment service to our top clients from our portfolio. we are currently seeking a engineer to join one of our clients' teams. if you're looking for an exciting opportunity to grow in a innovative environment, this could be the perfect fit for you.what you will do:develop and maintain applications.deliver and maintainable software.translate business requirements into technical solutions.implement, review, support and debug required scopewrite tech specs and...
======================================================================


======================================================================
📌 Job #159
🏷️  Title: Senior Quality Assurance Automation Engineer
🏢 Company: AlphaSights
🔧 Tech Stacks Found: {'languages': ['java', 'javascript', 'python', 'typescript'], 'devops': ['kubernetes'], 'testing': ['cypress', 'playwright'], 'others_general': ['automation', 'backend', 'cloud', 'distributed systems', 'frontend', 'infrastructure', 'manual testing', 'mentoring', 'nosql', 'product management', 'security', 'sql', 'testing']}
📊 Similarity: 0.4148
🔥 Compatibility Score: 79.07
----------------------------------------------------------------------
📝 Description:
the role: alphasights is seeking a highly experienced, self-driven senior qa engineer to join our software engineering team. we are a digital business in which continuous uptime, product quality, and user experience are critical to success. the role of the qa engineer therefore represents a visible and valued opportunity to have an immediate impact. working alongside software engineering and , you will lead the design and implementation of automated solutions that scale across our platform, ensu...
======================================================================


======================================================================
📌 Job #238
🏷️  Title: Senior Java Developer
🏢 Company: Penguin Formula
🔧 Tech Stacks Found: {'languages': ['go', 'java', 'python'], 'frontend_frameworks': ['angular'], 'backend_frameworks': ['spring'], 'cloud': ['aws'], 'devops': ['docker', 'kubernetes'], 'databases_sql': ['mysql', 'postgresql'], 'big_data': ['kafka'], 'messaging': ['rabbitmq'], 'others_general': ['api', 'automation', 'backend', 'cloud', 'debugging', 'distributed systems', 'frontend', 'infrastructure', 'nosql', 'rest', 'security', 'solid', 'sql']}
📊 Similarity: 0.4153
🔥 Compatibility Score: 77.02
----------------------------------------------------------------------
📝 Description:
company descriptionwecookit is an international software house that delivers software development to its corporate customers by providing highly skilled, communicative it professionals to build their customized products through outsourcing, nearshoring and turn-key projects’ solutions.how do we differentiate ourselves? by investing in the professional growth and personal care of our software developers. we provide them with a premium service so that they can do the same for our customers.our tal...
======================================================================


======================================================================
📌 Job #217
🏷️  Title: Senior Platform Engineer
🏢 Company: Feedzai
🔧 Tech Stacks Found: {'languages': ['go', 'python'], 'cloud': ['aws', 'gcp'], 'devops': ['docker', 'kubernetes', 'terraform'], 'cicd': ['jenkins'], 'monitoring': ['grafana', 'prometheus'], 'others_general': ['automation', 'cloud', 'computer science', 'data science', 'distributed systems', 'diversity', 'gitlab', 'infrastructure', 'nosql', 'product development', 'product management', 'risk management', 'security']}
📊 Similarity: 0.4171
🔥 Compatibility Score: 76.47
----------------------------------------------------------------------
📝 Description:
feedzai is the world’s first riskops platform for financial , and the market leader in safeguarding global commerce with today’s most advanced -based platform, powered by machine learning and artificial intelligence. feedzai is securing the transition to a cashless world while enabling digital trust in every transaction and payment type. the world’s largest banks, processors, and retailers trust feedzai to protect trillions of dollars and manage risk while improving the customer experience for e...
======================================================================


======================================================================
📌 Job #160
🏷️  Title: Backend Developer Support
🏢 Company: Rocket Code (AL-I Digital Solutions S.A. de C.V.)
🔧 Tech Stacks Found: {'languages': ['bash', 'python'], 'backend_frameworks': ['node'], 'cloud': ['aws', 'gcp'], 'databases_sql': ['mysql', 'postgresql'], 'databases_nosql': ['mongodb'], 'others_general': ['automation', 'backend', 'cloud', 'debugging', 'fintech', 'git', 'postman', 'scripting', 'solid', 'technical support']}
📊 Similarity: 0.408
🔥 Compatibility Score: 75.23
----------------------------------------------------------------------
📝 Description:
join the ai revolution with rocket code!at rocket code, we're not just developers — we're dreamers, doers, and disruptors. as a rapidly growing company renowned for building and optimizing technological platforms, we are at the forefront of making ai work for you, turning market buzz into groundbreaking realities. our disruptive, ai-first approach drives us to seek new ways of working, prioritizing operational efficiency and transforming the software development industry. we need passionate indi...
======================================================================


======================================================================
📌 Job #284
🏷️  Title: Data Scientist
🏢 Company: CloudWalk
🔧 Tech Stacks Found: {'languages': ['python'], 'cloud': ['google cloud'], 'ml_ai': ['pytorch', 'tensorflow'], 'others_general': ['cloud', 'data science', 'data visualization', 'distributed systems', 'fintech', 'research', 'risk management', 'solid', 'sql']}
📊 Similarity: 0.4064
🔥 Compatibility Score: 74.69
----------------------------------------------------------------------
📝 Description:
about cloudwalk:we are not just another unicorn. we are a pack of dreamers, makers, and tech enthusiasts building the future of payments. with millions of happy customers and a hunger for , we're now expanding our neural network - literally and metaphorically.about the team:the risk team is responsible for building the defense layer that keeps cloudwalk, its merchants, and users safe. we keep our ecosystem healthy by tracking down malicious activity and maintaining regulatory compliance while pr...
======================================================================


======================================================================
📌 Job #265
🏷️  Title: Senior Fullstack Developer
🏢 Company: Redbee
🔧 Tech Stacks Found: {'languages': ['c'], 'frontend_frameworks': ['react'], 'others_general': ['graphql', 'rest']}
📊 Similarity: 0.3596
🔥 Compatibility Score: 74.68
----------------------------------------------------------------------
📝 Description:
buscamos profesionales con curiosidad y pasión, jugadores de equipo, que quieran crecer, innovar y aprender de las últimas tecnologías. hacemos diferente y estamos en movimiento!tenemos una cultura a. .t.i.va y nuestro propósito es ayudarte a elegir el mejor camino para que la rompas.¿qué hacemos como senior developer en redbee?desarrollar nuevas funcionalidades en aplicaciones utilizando nest.js y , bff, arquitecturas orientadas a microservicios. escribir código bien estructurado asegurando man...
======================================================================


======================================================================
📌 Job #153
🏷️  Title: Senior Backend Software Engineer
🏢 Company: Squad
🔧 Tech Stacks Found: {'languages': ['python'], 'cloud': ['aws'], 'others_general': ['cloud', 'healthcare', 'infrastructure', 'mental health', 'product development', 'saas', 'security', 'startup', 'system architecture']}
📊 Similarity: 0.397
🔥 Compatibility Score: 74.46
----------------------------------------------------------------------
📝 Description:
about our clientour client is a privately held, early-stage company pioneering the use of artificial intelligence to transform paradigms and develop a new category of psychological fitness. the is focused on creating a world where individuals and communities are empowered to proactively identify and address psychological challenges and concerns.this company is backed by a leading enterprise known for conceiving, building, and supporting ventures that invent breakthrough technologies across , agr...
======================================================================


======================================================================
📌 Job #253
🏷️  Title: Senior Data Engineer
🏢 Company: ID5
🔧 Tech Stacks Found: {'languages': ['java', 'kotlin', 'python'], 'frontend_frameworks': ['vue'], 'backend_frameworks': ['spring'], 'cloud': ['aws', 'azure', 'gcp'], 'devops': ['kubernetes'], 'databases_sql': ['postgres', 'snowflake'], 'databases_nosql': ['cassandra'], 'big_data': ['airflow', 'databricks', 'flink', 'kafka', 'spark', 'trino'], 'bi_analytics': ['superset'], 'infra': ['apache'], 'monitoring': ['grafana'], 'others_general': ['advertising', 'analytics', 'api', 'backend', 'cloud', 'computer science', 'data engineering', 'diversity', 'infrastructure', 'nosql', 'solid', 'sql']}
📊 Similarity: 0.4104
🔥 Compatibility Score: 74.31
----------------------------------------------------------------------
📝 Description:
id5 enables addressable and measurable to support the growth of the digital economy and provide free and safe access to content and services. technical changes, signal loss, and increasingly more stringent data protection regulations require new, advanced technologies that enable audience addressability while respecting people’s privacy preferences. id5 has risen to this challenge and developed solutions that support publishers’ and marketers’ need for better addressability. its laser focus on i...
======================================================================


======================================================================
📌 Job #227
🏷️  Title: Software Engineer Intern
🏢 Company: Branch International
🔧 Tech Stacks Found: {'languages': ['java', 'kotlin', 'python', 'ruby'], 'mobile': ['android'], 'others_general': ['backend', 'computer science', 'distributed systems', 'fintech', 'open source', 'solid']}
📊 Similarity: 0.3997
🔥 Compatibility Score: 74.22
----------------------------------------------------------------------
📝 Description:
branch overviewbranch is a leading ai-based lending with 50m+ downloads across india and africa. we use alternative data to reach millions of people that are largely excluded from the financial sector.headquartered in silicon valley with operations in india, nigeria and kenya, branch is a for-profit, socially conscious company built for scale and impact. our mission-driven team—founded and led by the former ceo of kiva.org—now spans 400+ employees globally. we’re backed by investors such as andr...
======================================================================


======================================================================
📌 Job #280
🏷️  Title: AI Engineer
🏢 Company: Addepto
🔧 Tech Stacks Found: {'languages': ['python', 'typescript'], 'frontend_frameworks': ['react'], 'backend_frameworks': ['fastapi', 'node'], 'cloud': ['aws', 'azure', 'gcp'], 'devops': ['docker'], 'big_data': ['databricks'], 'others_general': ['backend', 'big data', 'cloud', 'data engineering', 'data science', 'documentation', 'frontend', 'git', 'infrastructure', 'nosql', 'onboarding', 'solid', 'sql']}
📊 Similarity: 0.3922
🔥 Compatibility Score: 74.18
----------------------------------------------------------------------
📝 Description:
addepto is a leading ai consulting and company that builds scalable, roi-focused ai solutions for some of the world's largest enterprises and pioneering startups, including rolls royce, continental, porsche, abb, and wgu. with our exclusive focus on artificial intelligence and , we help organizations unlock the full potential of their data through systems designed for measurable business impact and long-term growth.beyond client projects, we have developed our own product offerings born from rea...
======================================================================


======================================================================
📌 Job #172
🏷️  Title: RPA Developer
🏢 Company: Realtime Analytics By Procalidad
🔧 Tech Stacks Found: {'languages': ['python'], 'cloud': ['aws', 'azure', 'google cloud'], 'others_general': ['automation', 'git', 'nlp', 'rest', 'scripting', 'sql']}
📊 Similarity: 0.3665
🔥 Compatibility Score: 73.58
----------------------------------------------------------------------
📝 Description:
rpa developer with ai/mlwe are looking for a motivated and goal-oriented rpa developer with artificial intelligence and machine learning to join our team. the rpa developer creates and maintains robotic process (rpa) solutions integrated with artificial intelligence and machine learning capabilities. designs intelligent bots that can learn, adapt, and make data-driven decisionskey responsibilities:✅ develop rpa bots using uipath, anywhere, or blue prism ✅ integrate ml models to improve automated...
======================================================================


======================================================================
📌 Job #222
🏷️  Title: Senior Angular Developer
🏢 Company: INNOCV Solutions S.L.U.
🔧 Tech Stacks Found: {'languages': ['javascript', 'typescript'], 'frontend_frameworks': ['angular'], 'others_general': ['agile', 'diversity', 'insurance', 'solid', 'testing', 'web applications']}

### Rodando Pipeline

In [ ]:
# Pipe- gera_dados
pipeline_remotive_tech_jobs() #faz request e salva em data/raw
pipeline() # pega os dados salvos em data/raw trata eles e salva em processed com as tech_stacks, soft_skills e description tratados
generate_embeddings_df() # Utiliza API openIA pra gerar embeddings para cada vaga,

✔ Arquivo salvo em: ../data/raw/tech_jobs.json
✔ Salvo 347 tech jobs em tech_jobs.json
✔ Arquivo salvo em: ../data/processed/jobs_processed.json
✅ CSV salvo em: ../data/processed/jobs_with_embeddings.csv

,id,url,title,company_name,company_logo,category,job_type,publication_date,candidate_required_location,salary,description,tech_stacks_found,soft_skills_found,company_logo_url,embedding
0,2079713,https://remotive.com/remote-jobs/qa/qa-enginee...,QA Engineer,PatientNow,https://remotive.com/job/2079713/logo,QA,full_time,2025-11-21T20:50:23,USA,,"the roleas our founding qa engineer, you’ll bu...","{'frontend_frameworks': ['next.js'], 'testing'...","{'communication': ['communication'], 'attentio...",NaN,"[-0.028529442846775055, 0.008444409817457199, ..."
1,2070452,https://remotive.com/remote-jobs/software-deve...,Quantitative Research Team Lead (Completed),Apexver,https://remotive.com/job/2070452/logo,Software Development,full_time,2025-11-21T20:00:41,Worldwide,$180k + performance bonus,"role overview as the quantitative team lead, y...","{'languages': ['c', 'python'], 'others_general...","{'communication': ['communication'], 'teamwork...",NaN,"[-0.04142270237207413, 0.0007170444587245584, ..."
2,2079702,https://remotive.com/remote-jobs/qa/sr-perform...,Sr. Performance Tester,Tietoevry,https://remotive.com/job/2079702/logo,QA,full_time,2025-11-21T18:51:44,India,,company descriptionwe are developers of digita...,"{'languages': ['java', 'python'], 'cloud': ['a...","{'communication': ['communication'], 'creativi...",NaN,"[-0.04076246917247772, -0.00853677000850439, -..."
3,2080480,https://remotive.com/remote-jobs/software-deve...,Senior Software Engineer - Platform Development,Tanium,https://remotive.com/job/2080480/logo,Software Development,full_time,2025-11-21T16:50:18,Canada,"c$200,000 to c$220,000",the basics: as a tanium senior software engine...,"{'languages': ['c', 'go'], 'cloud': ['aws', 'a...","{'teamwork': ['collaboration'], 'time_manageme...",NaN,"[-0.03667346388101578, -0.03649427741765976, -..."
4,2080479,https://remotive.com/remote-jobs/software-deve...,Staff Application Security Engineer,PlayStation Global,https://remotive.com/job/2080479/logo,Software Development,full_time,2025-11-21T16:50:17,USA,"$198,200 - $297,400 usd",why playstation? playstation isn’t just the be...,"{'languages': ['c', 'java', 'javascript', 'pyt...","{'communication': ['communication'], 'teamwork...",NaN,"[-0.010802310891449451, -0.02232527732849121, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,2054061,https://remotive.com/remote-jobs/software-deve...,Full Stack Developer,Getwingapp,https://remotive.com/job/2054061/logo,Software Development,full_time,2025-08-31T00:51:25,India,inr 15 lpa - 25 lpa,about uswing is seeking elite talent to join m...,"{'languages': ['go', 'javascript', 'php', 'pyt...","{'leadership': ['leadership'], 'work_style': [...",NaN,"[-0.03661661967635155, -0.016772883012890816, ..."
343,2053123,https://remotive.com/remote-jobs/qa/software-d...,Software Development Engineer in Test,"Bayesian Health, Inc.",https://remotive.com/job/2053123/logo,QA,full_time,2025-08-27T22:51:54,USA,,software development engineer in testin briefw...,"{'testing': ['cypress', 'selenium'], 'producti...","{'teamwork': ['collaboration'], 'problem_solvi...",NaN,"[0.0002656708238646388, 0.02247590944170952, -..."
344,2052625,https://remotive.com/remote-jobs/software-deve...,Internal Tooling Engineer Lead,Protex%20AI,https://remotive.com/job/2052625/logo,Software Development,full_time,2025-08-27T22:50:54,Hungary,,"about us:at protex ai, we are at the forefront...","{'languages': ['go', 'javascript', 'python'], ...","{'communication': ['communication'], 'accounta...",NaN,"[-0.025792598724365234, 0.000583440123591572, ..."
345,2052631,https://remotive.com/remote-jobs/software-deve...,Senior Fullstack Engineer,Ciklum,https://remotive.com/job/2052631/logo,Software Development,full_time,2025-08-27T22:50:53,Poland,,ciklum is looking for a senior engineer to joi...,"{'languages': ['java'], 'backend_frameworks': ...","{'teamwork': ['collaboration'], 'adaptability'...",NaN,"[-0.033299144357442856, -0.04704069346189499, ..."
346,2052198,https://remotive.com/remote-jobs/software-deve...,Senior Front-End Web Developer,Aequilibrium Software Inc.,https://remotive.com/job/2052198/logo,Software Development,full_time,2025-08-26T20:51:11,Canada,,aequilibrium is seeking a senior front-end web...,"{'languages': ['typescript'], 'frontend_framew...","{'teamwork': ['collaboration'], 'time_manageme...",NaN,"[-0.022271130234003067, -0.025897515937685966,..."

## -------------------------------------------------------------------------

## Recebendo API e criando pipeline

In [11]:
### REQ Recebe currículos da API ### 

import requests
import json

url = "https://remotive.com/api/remote-jobs?limit=1"

response = requests.get(url)
response.raise_for_status()

raw_one_job = response.json()["jobs"][0]  # full raw dict for the job

print(json.dumps(raw_one_job, indent=2))

{
  "id": 1987878,
  "url": "https://remotive.com/remote-jobs/education/language-teachers-1987878",
  "title": "Language teachers",
  "company_name": "AE Virtual Class S.A",
  "company_logo": "https://remotive.com/job/1987878/logo",
  "category": "Education",
  "tags": [
    "teaching"
  ],
  "job_type": "part_time",
  "publication_date": "2025-11-21T05:30:55",
  "candidate_required_location": "Americas",
  "salary": "$10k",
  "description": "<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\"><strong>Description:</strong></p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">AE Virtual Class, member of Academia Europea Group, leader in language teaching, with 56 years of experience and the largest teaching staff in the Americas! We are looking for language enthusiasts who want to be part of our great family! Experience is NOT a requirement! We teach you how to teach!</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">\u00a0</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\"><strong>Job Requirements:</strong></p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Laptop (with webcam).</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Stable internet connection (15 Mbps).</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Attitude.</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Dynamism.</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Afternoon and/or evening shifts (Central America time zone).</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Excellent Mandarin, German, Italian or French proficiency (C1-C2).</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">\u00a0</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\"><strong>Main responsibilities of the position:</strong></p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Motivate students.</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Generate interest in cultures and languages.</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Prepare reports.</p>\n<p style=\"margin-bottom: 10px; caret-color: #6a6a6a; color: #6a6a6a;\">Evaluations.</p>\n<img src=\"https://remotive.com/job/track/1987878/blank.gif?source=public_api\" alt=\"\"/>",
  "company_logo_url": "https://remotive.com/job/1987878/logo"
}

### Limpando tags HTML da descrição

In [ ]:
import re

def clean_html(text: str) -> str:
    """Remove todas as tags HTML."""
    return re.sub(r"<[^>]+>", "", text)


def clean_jobs(raw_json: dict) -> list:
    """
    Recebe o JSON da API e retorna uma nova lista de jobs
    com "description" limpa.
    """
    raw_jobs = raw_json["jobs"]
    clean_jobs = []

    for job in raw_jobs:
        new_job = job.copy()
        new_job["description"] = clean_html(job["description"])
        clean_jobs.append(new_job)

    return clean_jobs


# ----------------------------- 
clean_list = clean_jobs(response.json())
print(clean_list[0]["description"])

Description:
AE Virtual Class, member of Academia Europea Group, leader in language teaching, with 56 years of experience and the largest teaching staff in the Americas! We are looking for language enthusiasts who want to be part of our great family! Experience is NOT a requirement! We teach you how to teach!

Job Requirements:
Laptop (with webcam).
Stable internet connection (15 Mbps).
Attitude.
Dynamism.
Afternoon and/or evening shifts (Central America time zone).
Excellent Mandarin, German, Italian or French proficiency (C1-C2).

Main responsibilities of the position:
Motivate students.
Generate interest in cultures and languages.
Prepare reports.
Evaluations.

### Request Aprimorada Apenas com vagas Tech

In [15]:
import requests
import json
import os

# Categorias realmente tech
TECH_CATEGORIES = [
    "software-development",
    "ai-ml",
    "data",
    "devops",
    "qa"
]

def get_remotive_tech_jobs():
    url = "https://remotive.com/api/remote-jobs"
    response = requests.get(url)
    data = response.json()

    raw_jobs = data.get("jobs", [])

    tech_jobs = []

    for job in raw_jobs:
        category_slug = job.get("category", "").lower().replace(" ", "-")

        if category_slug in TECH_CATEGORIES:
            tech_jobs.append(job)
    return tech_jobs


def save_to_json(data, filename="tech_jobs.json"):
    # Caminho final: ../data/raw/tech_jobs.json
    save_path = os.path.join("..", "data", "raw", filename)

    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    with open(save_path, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)

    print(f"Arquivo salvo em: {save_path}")


tech_jobs = get_remotive_tech_jobs()
save_to_json(tech_jobs)

print(f"Salvo {len(tech_jobs)} tech jobs em tech_jobs.json")

Arquivo salvo em: ../data/raw/tech_jobs.json
Salvo 346 tech jobs em tech_jobs.json

### Retirada de stacks e softskills

In [ ]:
import json
import re
from pathlib import Path


# --------------------------
# 1. Caminhos
# --------------------------
RAW_PATH = Path("../data/raw/tech_jobs.json")
PROCESSED_PATH = Path("../data/processed/jobs_processed.json")
SUPPORT_DIR = Path("../support")


# --------------------------
# 3. Carregar tech/soft maps
# --------------------------
def load_support_maps():
    with open(SUPPORT_DIR / "tech_stack.json", "r", encoding="utf-8") as f:
        tech_map = json.load(f)

    with open(SUPPORT_DIR / "soft_skills.json", "r", encoding="utf-8") as f:
        soft_map = json.load(f)

    tech_map = {k.lower(): [v.lower() for v in values] for k, values in tech_map.items()}
    soft_map = {k.lower(): [v.lower() for v in values] for k, values in soft_map.items()}

    return tech_map, soft_map


# --------------------------
# 4. Extração + remoção → RETORNA macro + variações usadas
# --------------------------
def extract_skill_map(description: str, skill_map: dict):
    desc = description.lower()

    found = {}   # exemplo: {"python": ["python developer", "python3"]}

    for macro, variations in skill_map.items():
        matches = []
        for var in variations:
            if var in desc:
                matches.append(var)
                desc = desc.replace(var, "")  # remover do texto

        if matches:
            found[macro] = matches

    desc = re.sub(r"\s+", " ", desc).strip()
    return desc, found


# --------------------------
# 5. Processar cada job
# --------------------------
def process_job(job, tech_map, soft_map):

    desc = strip_html(job.get("description", "")).lower()

    # tech
    desc, tech_matches = extract_skill_map(desc, tech_map)

    # soft
    desc, soft_matches = extract_skill_map(desc, soft_map)

    job["description"] = desc
    job["tech_stacks_found"] = tech_matches
    job["soft_skills_found"] = soft_matches

    job.pop("tags", None)

    return job


# --------------------------
# 6. EXECUTAR PIPELINE E SALVAR
# --------------------------
def main():
    tech_map, soft_map = load_support_maps()

    with open(RAW_PATH, "r", encoding="utf-8") as f:
        raw_jobs = json.load(f)

    processed = [process_job(job, tech_map, soft_map) for job in raw_jobs]

    PROCESSED_PATH.parent.mkdir(parents=True, exist_ok=True)

    with open(PROCESSED_PATH, "w", encoding="utf-8") as f:
        json.dump(processed, f, indent=4, ensure_ascii=False)

    print(f"✔ Arquivo salvo em: {PROCESSED_PATH}")


if __name__ == "__main__":
    main()

✔ Arquivo salvo em: ../data/processed/jobs_processed.json

## Vetorizando campo description para usar como um dos parametros para nota a "proximidade" dos vetores

In [54]:
#load curriculo

curriculo = """
OBJECTIVE
Seeking career growth opportunities in the field of software development.

EDUCATION
Bachelor of Computer Science, Universidade Federal do ABC 
Expected Graduation: 2026

SKILLS
Main Technical Skills: Python, SQL, ETL, Java, Git
Soft Skills: Communication, Adaptability, Analytical Thinking, Proactivity
Github Portfolio: https://github.com/Netreck
Languages: English, Portuguese

PROFESSIONAL EXPERIENCE
Intern – Bank of America (Jun 2025 – Present)
VP Global Technology – Tech Rotation Program
• Developed test automation and tools to support QA teams in payment systems.
• Contributed to internal automation and process optimization projects.
• Technologies: Java, Python, Git, SQL, Node.js, HTML, CSS, Octane, QTest, Matera.

Data Intern – Vivo (Telefônica Brasil) (Jan 2025 – Jun 2025)
VP Engineering & Customer Services
• Generated, monitored, and analyzed operational KPIs focused on efficiency and customer experience.
• Built Machine Learning solutions to modernize and improve operational results.
• Technologies: Python, SQL, TensorFlow, Power BI, Excel.

EXTRACURRICULAR ACTIVITIES
Member – Green Team Hacker Club (Jan 2024 – Jan 2025)
Project Manager – Data Projects, Green Team Hacker Club (Jan 2025 – Present)
Federal University of ABC (UFABC) – Santo André, SP
• Official student-led organization linked to UFABC.
• Participated in classes and projects related to Data Science.
• Defined and managed technology stack for projects, considering scalability, performance, and integration.
• Managed team activities including task delegation, progress tracking, and technical support.
• Worked with ETL, process automation (pipelines), SQL, PostgreSQL, Data Visualization (Seaborn, Matplotlib), Data Modeling, Machine Learning models (Scikit-learn, TensorFlow), model deployment via APIs, MLflow, and LLMs.
"""

In [36]:
import pandas as pd

df = pd.read_json("../data/processed/jobs_processed.json")

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           346 non-null    int64
 1   url                          346 non-null    object
 2   title                        346 non-null    object
 3   company_name                 346 non-null    object
 4   company_logo                 346 non-null    object
 5   category                     346 non-null    object
 6   job_type                     346 non-null    object
 7   publication_date             346 non-null    object
 8   candidate_required_location  346 non-null    object
 9   salary                       346 non-null    object
 10  description                  346 non-null    object
 11  tech_stacks_found            346 non-null    object
 12  soft_skills_found            346 non-null    object
 13  company_logo_url             9 non-null      object
dtypes: int64(1), object(13)
memory usage: 38.0+ KB

In [38]:
df.head()

,id,url,title,company_name,company_logo,category,job_type,publication_date,candidate_required_location,salary,description,tech_stacks_found,soft_skills_found,company_logo_url
0,2079700,https://remotive.com/remote-jobs/qa/junior-per...,Junior Performance QA Engineer,Veeam Software,https://remotive.com/job/2079700/logo,QA,full_time,2025-11-20T14:50:36,Poland,,"veeam, the #1 global maket leade in data esili...","{'languages': ['c', 'go', 'rust', 'r'], 'front...",{'creativity': ['ideation']},NaN
1,2079712,https://remotive.com/remote-jobs/software-deve...,Senior Backend Engineer,Roompricegenie,https://remotive.com/job/2079712/logo,Software Development,full_time,2025-11-20T10:50:04,Europe,,"about oompiegenie ✨🧞‍♂️founded in 2017, oompie...","{'languages': ['python', 'c', 'go', 'r'], 'fro...","{'creativity': ['innovation'], 'work_style': [...",NaN
2,2079711,https://remotive.com/remote-jobs/software-deve...,Senior Golang Engineer,Scale3c,https://remotive.com/job/2079711/logo,Software Development,full_time,2025-11-20T10:50:04,Europe,,join ou team to eshape dial logistis though ou...,"{'languages': ['c', 'go', 'r'], 'frontend_fram...","{'work_style': ['initiative', 'autonomy']}",NaN
3,2079698,https://remotive.com/remote-jobs/qa/senior-qa-...,Senior QA Automation Engineer,Cookunity,https://remotive.com/job/2079698/logo,QA,full_time,2025-11-20T08:50:39,Argentina,,about ook: food has lost its soul to moden onv...,"{'languages': ['java', 'typescript', 'c', 'go'...","{'creativity': ['ideation'], 'time_management'...",NaN
4,2079707,https://remotive.com/remote-jobs/software-deve...,iOS Developer,Just Play,https://remotive.com/job/2079707/logo,Software Development,full_time,2025-11-20T08:50:34,Germany,,justplay is looking fo an develope to play a k...,"{'languages': ['c', 'go', 'swift', 'r'], 'fron...",{},NaN

In [ ]:
### Tratando colunas
import ast

cols_list = [ "tech_stacks_found", "soft_skills_found"]

for col in cols_list:
    df[col] = df[col].apply(
        lambda x: ast.literal_eval(x) if isinstance(x, str) else x
    )

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 346 entries, 0 to 345
Data columns (total 14 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           346 non-null    int64
 1   url                          346 non-null    object
 2   title                        346 non-null    object
 3   company_name                 346 non-null    object
 4   company_logo                 346 non-null    object
 5   category                     346 non-null    object
 6   job_type                     346 non-null    object
 7   publication_date             346 non-null    object
 8   candidate_required_location  346 non-null    object
 9   salary                       346 non-null    object
 10  description                  346 non-null    object
 11  tech_stacks_found            346 non-null    object
 12  soft_skills_found            346 non-null    object
 13  company_logo_url             9 non-null      object
dtypes: int64(1), object(13)
memory usage: 38.0+ KB

In [ ]:
## Faz uma chamada por vaga para criar embbendingds das vagas

import pandas as pd

df["embedding"] = df["description"].apply(embeddings.embed_query)

In [44]:
import numpy as np

def cosine_similarity(a, b):
    a = np.array(a)
    b = np.array(b)
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [55]:
### embendding curriculo
curriculo_emb = embeddings.embed_query(curriculo)

In [56]:
import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# df_original é o seu df atual
df_original = df.copy()

# Calcula similaridade
df_original["embedding_similarity"] = df_original["embedding"].apply(
    lambda v: float(cosine_similarity(
        np.array(curriculo_emb).reshape(1, -1),
        np.array(v).reshape(1, -1)
    )[0][0])
)

# Ordena pela similaridade (desc)
df_sorted = df_original.sort_values(by="embedding_similarity", ascending=False)

df_sorted[["description", "tech_stacks_found", "embedding_similarity"]].head()

,description,tech_stacks_found,embedding_similarity
151,the ole: alphasights is seeking a highly expei...,"{'languages': ['python', 'java', 'typescript',...",0.435639
234,ompany desiptionweookit is an intenational sof...,"{'languages': ['python', 'java', 'c', 'go', 'r...",0.433487
276,addepto is a leading ai onsulting and data ene...,"{'languages': ['python', 'typescript', 'c', 'g...",0.423877
213,feedzai is the wold’s fist iskops platfom fo f...,"{'languages': ['python', 'c', 'go', 'rust', 'r...",0.415411
240,teavision tehnologies is a neashoe softwae out...,"{'languages': ['c', 'go', 'r', 'lua'], 'fronte...",0.413761

In [57]:
for idx, row in df_sorted.iterrows():
    print("="*70)
    print(f"📌 Job #{idx}")
    print(f"🏷️  Title: {row.get('title', 'N/A')}")
    print(f"🏢 Company: {row.get('company_name', 'N/A')}")
    print(f"🔧 Tech Stacks Found: {row.get('tech_stacks_found', [])}")
    print(f"📊 Similarity: {row['embedding_similarity']:.4f}")
    print("-"*70)
    print(f"📝 Description:\n{row.get('description','')[:500]}...")
    print("="*70)
    print()

======================================================================
📌 Job #151
🏷️  Title: Senior Quality Assurance Automation Engineer
🏢 Company: AlphaSights
🔧 Tech Stacks Found: {'languages': ['python', 'java', 'typescript', 'c', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'others_general': ['sql', 'automation', 'manual testing', 'testing', 'git', 'ios', 'api', 'unity']}
📊 Similarity: 0.4356
----------------------------------------------------------------------
📝 Description:
the ole: alphasights is seeking a highly expeiened, self-diven senio qa enee to join ou softwae eneeing team. we ae a dial business in whih ontinuous uptime, podut quay, and use expeiene ae itial to suess. the ole of the qa enee theefoe epesents a visible and valued oppot to have an immediate impat. woking alongside softwae eneeing and podut management, you will lead the design and implementation of automated solutions that sale aoss ou platfom, ensuing ou appliations ae eliable, salable, and me...
======================================================================

======================================================================
📌 Job #234
🏷️  Title: Senior Java Developer
🏢 Company: Penguin Formula
🔧 Tech Stacks Found: {'languages': ['python', 'java', 'c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'cloud': ['aws'], 'databases_sql': ['mysql'], 'big_data': ['kafka'], 'ml_ai': ['llama'], 'others_general': ['sql', 'automation', 'solid', 'ios', 'api', 'unity']}
📊 Similarity: 0.4335
----------------------------------------------------------------------
📝 Description:
ompany desiptionweookit is an intenational softwae house that delives softwae development to its opoate ustomes by poviding highly skilled, ommuniative it pofessionals to build thei ustomized poduts though outsouing, neashoing and tun-key pojets’ solutions.how do we diffeentiate ouselves? by investing in the pofessional gowth and pesonal ae of ou softwae developes. we povide them with a pemium sevie so that they an do the same fo ou ustomes.ou talented team holds softwae enees and sales expets, ...
======================================================================

======================================================================
📌 Job #276
🏷️  Title: AI Engineer
🏢 Company: Addepto
🔧 Tech Stacks Found: {'languages': ['python', 'typescript', 'c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['node', 'fastapi', 'gin'], 'cloud': ['aws'], 'others_general': ['sql', 'solid', 'git', 'ios', 'big data', 'unity']}
📊 Similarity: 0.4239
----------------------------------------------------------------------
📝 Description:
addepto is a leading ai onsulting and data eneeing ompany that builds salable, oi-foused ai solutions fo some of the wold's lagest entepises and pioneeing statups, inluding olls oye, ontinental, poshe, abb, and wgu. with ou exlusive fous on atifiial intelligene and , we help oganizations unlok the full potential of thei data though systems designed fo measuable business impat and long-tem gowth.beyond lient pojets, we have developed ou own podut offeings bon fom eal-life lient insights and halle...
======================================================================

======================================================================
📌 Job #213
🏷️  Title: Senior Platform Engineer
🏢 Company: Feedzai
🔧 Tech Stacks Found: {'languages': ['python', 'c', 'go', 'rust', 'r', 'lua'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'cloud': ['aws'], 'cicd': ['jenkins'], 'others_general': ['sql', 'automation', 'git', 'unity']}
📊 Similarity: 0.4154
----------------------------------------------------------------------
📝 Description:
feedzai is the wold’s fist iskops platfom fo finanial isk management, and the maket leade in safeguading global ommee with today’s most advaned loud-based isk management platfom, poweed by mahine leaning and atifiial intelligene. feedzai is seuing the tansition to a ashless wold while enabling dial t in evey tansation and payment type. the wold’s lagest banks, poessos, and etailes t feedzai to potet tillions of dollas and manage isk while impoving the ustome expeiene fo eveyday uses, without omp...
======================================================================

======================================================================
📌 Job #240
🏷️  Title: Full Stack Developer
🏢 Company: Teravision Technologies
🔧 Tech Stacks Found: {'languages': ['c', 'go', 'r', 'lua'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['node', 'gin'], 'cloud': ['aws'], 'databases_sql': ['mysql']}
📊 Similarity: 0.4138
----------------------------------------------------------------------
📝 Description:
teavision tehnologies is a neashoe softwae outsouing ompany with offies in olombia and usa and ove 170 pofessionals woking emotely woldwide. with ove 20 yeas of expeiene in design, development, and quay assuane, teavision tehnologies offes ustom solutions fo a wide ange of industies in the usa, euope, and latin ameia. why teavision tehnologies? hee at teavision tehnologies we ae poblem solves, with detail and objetive-oiented mindset and ae fist and foemost team playes. we want to be the next bi...
======================================================================

======================================================================
📌 Job #11
🏷️  Title: Junior Software Engineer
🏢 Company: Dev.Pro
🔧 Tech Stacks Found: {'languages': ['c', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'others_general': ['sql', 'solid', 'testing', '.net', 'git', 'ios', 'api', 'visual studio']}
📊 Similarity: 0.4096
----------------------------------------------------------------------
📝 Description:
🟢 at dev.po, we wok on pojets that impat millions of people aound the wold — but we know it’s the people behind the teh who make it all happen. we tuly value what makes eah peson unique and ae building a wokplae that’s inlusive, fiendly, and suppotive.we invite a poative softwae enee with and # skills to join ou team. in this ole, you’ll help build a leading healthae ost ontainment platfom that offes affodable health insuane plans fo self-insued employes, thid-paty administatos, ommeial payes, a...
======================================================================

======================================================================
📌 Job #57
🏷️  Title: Senior Data Engineer (AWS & Python)
🏢 Company: Proxify
🔧 Tech Stacks Found: {'languages': ['python', 'c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'cloud': ['aws'], 'databases_sql': ['snowflake'], 'big_data': ['kafka', 'flink', 'kinesis'], 'security': ['vault'], 'others_general': ['sql', 'solid', 'api', 'etl', 'amazon']}
📊 Similarity: 0.4066
----------------------------------------------------------------------
📝 Description:
the ole: we ae looking fo a senio data enee speializing in moden, loud-native data platfoms, with a stong fous on web sevies () and . you will be esponsible fo designing, building, and optimizing highly salable and eliable /elt pipelines and data waehouses that powe analytis, mahine leaning, and business intelligene fo ou lients. what we’e looking fo: 5+ yeas of pofessional expeiene in data eneeing expet pofiieny in fo data manipulation, sipting, and pipeline development (e.g., pandas, pyspak). ...
======================================================================

======================================================================
📌 Job #119
🏷️  Title: Senior Data Engineer (Azure)
🏢 Company: Proxify
🔧 Tech Stacks Found: {'languages': ['python', 'c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'databases_sql': ['snowflake'], 'others_general': ['sql', 'git', 'ios', 'api', 'etl', 'sla']}
📊 Similarity: 0.4057
----------------------------------------------------------------------
📝 Description:
the ole: we ae looking fo a senio data enee enee with deep expetise in moft azue to join ou fast-gowing netwok. you ae a pefet andidate if you ae gowth-oiented, you love what you do, and you enjoy woking on new ideas to develop exiting poduts. what we’e looking fo: 5+ yeas in data eneeing oles. advaned knowledge: omplex queies, pefomane tuning, stoed poedues. stong undestanding of azue tehnologies: azue database, data fatoy, et. poven expeiene in development, data integation, and pipeline ohesta...
======================================================================

======================================================================
📌 Job #93
🏷️  Title: Software Developer - Intern
🏢 Company: SYSTEM AUTOMATION CORPORATION
🔧 Tech Stacks Found: {'languages': ['java', 'c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'others_general': ['sql', 'automation', 'solid', 'testing', '.net', 'ios', 'saas', 'unity']}
📊 Similarity: 0.4024
----------------------------------------------------------------------
📝 Description:
apply job type intenship desiption intenship summe peiod -ealy deembe though mid januay 2026about the ompany system (sa) is a softwae vendo foused on poviding systems that suppot venment egulatoy management opeations.founded in the distit of olumbia in 1968 and oially ontated to develop and suppot the us amy euiting system (ontat held fo 42 yeas), sa has sine beome an industy leade in designing, developing, implementing, and maintaining ompehensive infomation management appliations fo venment eg...
======================================================================

======================================================================
📌 Job #77
🏷️  Title: Python Engineer
🏢 Company: TechBiz Global GmbH
🔧 Tech Stacks Found: {'languages': ['python', 'c', 'go', 'r', 'bash'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'cloud': ['aws'], 'databases_sql': ['mysql'], 'others_general': ['sql', 'solid', 'agile', 'unity', 'sla']}
📊 Similarity: 0.4012
----------------------------------------------------------------------
📝 Description:
at tehbiz global, we ae poviding euitment sevie to ou top lients fom ou potfolio. we ae uently seeking a enee to join one of ou lients' teams. if you'e looking fo an exiting oppot to gow in a innovative envionment, this ould be the pefet fit fo you.what you will do:develop and maintain appliations.delive and maintainable softwae.tante business equiements into tehnial solutions.implement, eview, suppot and debug equied sopewite teh spes and define pojet ahitetue.wite unit tests and integation tes...
======================================================================

======================================================================
📌 Job #149
🏷️  Title: QA Automation Engineer
🏢 Company: Sofka
🔧 Tech Stacks Found: {'languages': ['python', 'java', 'c', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'cicd': ['jenkins'], 'testing': ['selenium'], 'others_general': ['sql', 'automation', 'solid', 'testing', 'ios', 'seo']}
📊 Similarity: 0.4000
----------------------------------------------------------------------
📝 Description:
✨ ae you passionate about ensuing top-noth quay in web appliations? do you love woking with utting-edge tools and ontibuting to impatful pojets fo intenational lients? if so, we want you on ou team! ✨we’e looking fo a skilled qa enee with stong expeiene in playwight, sipt, and famewoks to join ou gowing team. you’ll be pat of exiting pojets fo u.s. lients, woking in a fully emote, multiultual envionment that enouages and ontinuous impovement.⚠️ impotant note:andidates must have 3+ yeas of expeie...
======================================================================

======================================================================
📌 Job #280
🏷️  Title: Data Scientist
🏢 Company: CloudWalk
🔧 Tech Stacks Found: {'languages': ['python', 'c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'others_general': ['sql', 'solid', 'ios', 'data visualization']}
📊 Similarity: 0.3990
----------------------------------------------------------------------
📝 Description:
about loudwalk:we ae not just anothe finteh union. we ae a pak of deames, makes, and teh enthusiasts building the futue of payments. with millions of happy ustomes and a hunge fo , we'e now expanding ou neual netwok - eally and metaphoially.about the team:the isk team is esponsible fo building the defense laye that keeps loudwalk, its mehants, and uses safe. we keep ou eosystem healthy by taking down maliious ativity and maintaining egulatoy ompliane while poviding the best use expeiene. you wil...
======================================================================

======================================================================
📌 Job #63
🏷️  Title: Front-End Engineer
🏢 Company: Trustly
🔧 Tech Stacks Found: {'languages': ['java', 'c', 'rust', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['node', 'gin'], 'others_general': ['ios', 'api', 'html', 'es6', 'etl']}
📊 Similarity: 0.3979
----------------------------------------------------------------------
📝 Description:
about the team: the develope expeiene team is esponsible fo the publily available develope doumentation, sdks &amp; libaies, s, and othe develope tools and poesses. ou fous is to offe the best expeiene fo developes and make tly the payment option developes pefe and eommend.what you'll do:eate and maintain featues in web inluding integation sipts appliations and be able to develop unit tests fo the same featues.esponsible fo investigating poblems in appliations in ollaboation with suppot teams, b...
======================================================================

======================================================================
📌 Job #76
🏷️  Title: Systems Analyst
🏢 Company: Dev.Pro
🔧 Tech Stacks Found: {'languages': ['c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'cloud': ['aws'], 'devops': ['k8s'], 'infra': ['linux'], 'monitoring': ['datadog'], 'others_general': ['solid']}
📊 Similarity: 0.3975
----------------------------------------------------------------------
📝 Description:
🟢 ae you in bazil, agentina o olombia? join us as we atively euit in these loations, offeing a omfotable emote envionment. submit you v in english, and we'll get bak to you!we invite a esponsible and eage-to-lean netwok opeations ente enee to join ou 24/7 suppot team, helping ensue the stabiy and pefomane of lient appliations and infastutue. ou lient povides etailes with a entalized, flexible, and seue payment platfom that enables ustomes to shop anytime and though any hannel. you’ll espond to i...
======================================================================

======================================================================
📌 Job #309
🏷️  Title: Mid-level Fullstack Engineer
🏢 Company: AlphaSights
🔧 Tech Stacks Found: {'languages': ['java', 'c', 'go', 'ruby', 'kotlin', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'others_general': ['ios', 'unity']}
📊 Similarity: 0.3973
----------------------------------------------------------------------
📝 Description:
the ole: we ae looking fo highly talented and diven softwae enees who take pide in thei wok, to expand ou eneeing team in the us. suessful andidates will join a oss funtional team inluding podut manages and designes woking losely with the est of ou business to delive woking ode that solves eal poblems fo both intenal and extenal ustomes. you will take owneship of the poblems that you team solves, ensuing a high level of quay in eveything that we elease, woking as pat of a top pefoming intenation...
======================================================================

======================================================================
📌 Job #6
🏷️  Title: Quality Engineer
🏢 Company: FusionHit
🔧 Tech Stacks Found: {'languages': ['python', 'c', 'go', 'rust', 'r'], 'frontend_frameworks': ['nextjs', 'lit'], 'backend_frameworks': ['node', 'gin'], 'cloud': ['aws'], 'testing': ['selenium', 'pytest'], 'others_general': ['automation', 'testing', 'git', 'ios', 'api']}
📊 Similarity: 0.3956
----------------------------------------------------------------------
📝 Description:
we ae looking fo a quay enee to join ou fast-paed, innovative ai team. this position involves and ensuing the eliabiy of high-visibiy intenal appliations built pimaily in and js, with potential ai integations in . you’ll ontibute to piloting advaned ai-quay eneeing tools and diving salable, automated stategies fo appliations that suppot ompany-wide podutivity.ou lient woks in the tehnology industy, deliveing intelligent solutions that enhane entepise effiieny. thei fous is on developing obust in...
======================================================================

======================================================================
📌 Job #293
🏷️  Title: Machine Learning Engineer
🏢 Company: Talencore
🔧 Tech Stacks Found: {'languages': ['python', 'java', 'c', 'go', 'r'], 'frontend_frameworks': ['next.js', 'lit'], 'backend_frameworks': ['fastapi', 'gin'], 'big_data': ['hive'], 'others_general': ['sql', 'agile', 'git', 'api', 'unity', 'sla']}
📊 Similarity: 0.3926
----------------------------------------------------------------------
📝 Description:
ou lient, an ai-foused statup based in toonto, anada, ae seeking a full stak / mahine leaning enee to delive high-impat podut featues using eat/ on the fontend and on the bakend. you will wok within a foused eneeing pod unde the dietion of a lead pojet enee, in lose ollaboation with podut manages. this ole offes the oppot to build podution-gade softwae in a fast-moving envionment while developing you tehnial skills and gowing into eneeing leadeship.loation: emote, pefeably in toonto/gtaemploymen...
======================================================================

======================================================================
📌 Job #152
🏷️  Title: Backend Developer Support
🏢 Company: Rocket Code (AL-I Digital Solutions S.A. de C.V.)
🔧 Tech Stacks Found: {'languages': ['python', 'c', 'go', 'r', 'bash'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['node', 'gin'], 'cloud': ['aws'], 'databases_sql': ['mysql'], 'big_data': ['hive'], 'others_general': ['sql', 'automation', 'solid', 'git', 'api', 'postman', 'unity']}
📊 Similarity: 0.3924
----------------------------------------------------------------------
📝 Description:
join the ai evolution with oket ode!at oket ode, we'e not just developes — we'e deames, does, and disuptos. as a dly gowing ompany enowned fo building and optimizing tehnologial platfoms, we ae at the foefont of making ai wok fo you, tuning maket buzz into goundbeaking eaies. ou disuptive, ai-fist appoah dives us to seek new ways of woking, pioitizing opeational effiieny and tansfoming the softwae development industy. we need passionate individuals to join us on this exiting jouney.why oket ode?...
======================================================================

======================================================================
📌 Job #52
🏷️  Title: Tech Lead Databricks Data Engineer
🏢 Company: Mitre Media
🔧 Tech Stacks Found: {'languages': ['python', 'java', 'c', 'go', 'r'], 'frontend_frameworks': ['lit'], 'backend_frameworks': ['gin'], 'cloud': ['aws'], 'big_data': ['hive'], 'bi_analytics': ['tableau'], 'others_general': ['sql', 'solid', 'git', 'ios', 'api', 'big data', 'etl']}
📊 Similarity: 0.3895
----------------------------------------------------------------------
📝 Description:

In [51]:
df_sorted.describe()

                 id  embedding_similarity
count  3.460000e+02            346.000000
mean   2.061732e+06              0.357449
std    6.522461e+04              0.042062
min    1.359476e+06              0.189209
25%    2.067722e+06              0.332695
50%    2.070674e+06              0.360880
75%    2.072912e+06              0.385635
max    2.079712e+06              0.444239

In [58]:
output_path = "../data/processed/database.csv"
df_sorted.to_csv(output_path, index=False)

print(f"Arquivo salvo em: {output_path}")

Arquivo salvo em: ../data/processed/database.csv